api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('',views.index,name='index'),
    path('image/',views.images,name='image'),
    path('user/',views.users,name='users'),
    path('user/<int:uid>/',views.get_user,name='get_user'),
    path('top/<str:bump>/',views.top,name="top")
]

bump/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('myauth.urls')),
    path('api/',include('api.urls')),
    path('',include('index.urls')),
]

index/urls.py
from django.urls import path,include
from . import views

app_name = 'index'

urlpatterns = [
    path('',views.index,name='index'),
    path('pull/<int:img_id>',views.pull,name='pull'),
    path('top',views.bump,name='bump'),
    path('top/<str:bump>',views.bump,name='top'),
    path('user/',views.user,name='user'),
    path('user/<int:uid>',views.user,name='userid'),
    path('loadimg/',views.loadimg,name='loadimg'),
    path('dev/',views.token,name='token'),
    path('dev/new_token',views.new_token,name='new_token')
]

myauth/urls.py
from django.urls import path
from . import views

app_name = 'myauth'

urlpatterns = [
  path('',views.auth,name='login'),
  path('logout/',views.log_out,name='logout'),
  path('reg/',views.reg,name='reg')
]

api/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Api(models.Model):
    token = models.CharField(max_length=255)
    user = models.ForeignKey(User,on_delete=models.CASCADE)

api/views.py
from django.shortcuts import render
from django.http import JsonResponse, Http404
from .api_funcs import api_token
from index.models import Image, Vote
from django.contrib.auth.models import User

# Create your views here.
@api_token
def index(request):
    return JsonResponse({'response' : "Доступ к API еcть"})

@api_token
def images(request):
    imgs = Image.objects.all()
    response = [{'img_url' : i.img_url, 'votes' : i.votes, 'user_id' : i.user_id} for i in imgs]
    return JsonResponse({'response' : response})

@api_token
def get_user(request,uid):
    try:
        user = User.objects.get(pk=uid)
        imgs = Image.objects.filter(user=user).all()
        user_images = [{'img_url' : i.img_url, 'votes' : i.votes, 'user_id' : i.user_id} for i in imgs]
        rating = sum([i['votes'] for i in user_images])
        response = {
            'username' : user.username,
            'rating' : rating,
            'user_images' : user_images,
        }
    except User.DoesNotExist:
        response = {'error' : 'Пользователя с данным id не существует' }
    finally:
        return JsonResponse({'response' : response})

@api_token
def users(request):
    users = User.objects.order_by('id').all()
    response = [{'id' : u.id, 'username' : u.username} for u in users]
    return JsonResponse({'response' : response})

@api_token
def top(request,bump = 'bump'):
    if bump == "bump":
        imgs = Image.objects.order_by('-votes').all()[:100]
    elif bump == "sage":
        imgs = Image.objects.order_by('votes').all()[:100]
    else:
        raise Http404("Страница не найдена")
    response = [{'img_url' : i.img_url, 'votes' : i.votes, 'user_id' : i.user_id} for i in imgs]
    return JsonResponse({'response' : response })

index/templates/api.html
{% extends 'base.html' %}
{% block 'content' %}
<h1>Токен API</h1>
<h3>{{token}}</h3>
<form action="{% url 'index:new_token' %}">
  <input type="submit" value="Обновить токен" class="btn btn-danger">
</form>
{% endblock %}

index/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Bump or Sage</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <style>
    body {
        padding-top: 70px;
        /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */

    }
    </style>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'index:index' %}">BUMP OR SAGE</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'index:top' 'bump' %}">TOP BUMP</a>
                    </li>
                    <li>
                        <a href="{% url 'index:top' 'sage' %}">TOP SAGE</a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li>
                        <a href="{% url 'index:user' %}">Моя страница</a>
                    </li>
                    <li>
                        <a href="{% url 'index:loadimg' %}">Загрузить картинку</a>
                    </li>
                    <li>
                        <a href="{% url 'index:token' %}">Api</a>
                    </li>
                    <li>
                        <a href="{% url 'myauth:logout' %}">Выйти</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'myauth:login' %}">Вход в систему</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <div class="row">
            <div class="col-lg-12 text-center">
              {% block 'content' %}
              {% endblock %}
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->

    <!-- jQuery Version 1.11.1 -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>

</html>

index/templates/index.html
{% extends 'base.html' %}
{% block 'content' %}
{% if img %}
<img src="{{img.img_url}}" class="img-responsive center-block" alt="Смешная (или нет) картинка" style="max-height:400px">
<form action="{% url 'index:pull' img.pk %}" method="POST">
  {% csrf_token %}
  <input type="submit" name="vote" value="BUMP" class="btn btn-primary">
  <input type="submit" name="vote" value="SAGE" class="btn btn-danger">
</form>
{% else %}
<p>На сегодня все картинки закончились!</p>
{% endif %}
{% endblock %}

index/templates/landing.html
{% extends 'base.html' %}
{% block 'content' %}
<h1>Скоро тут будет лендинг!</h1>
{% endblock %}

index/templates/list.html
{% extends 'base.html' %}
{% block 'content' %}
<h1>TOP {{top}}</h1>
<div class="row">

  {% for img in imgs %}
    <div class="col-md-3" style="height: 300px">
      <img class="img-responsive center-block" src="{{img.img_url}}" alt="" style="max-height: 90%">
      <div><a href="{% url 'index:userid' img.user.pk %}">{{img.user.username}}</a></div>
    </div>
  {% endfor %}

</div>
<div class="btn-group">
{% if imgs.has_previous %}
    <a class="btn btn-default" href="?page=1">1</a>
    <a class="btn btn-default" href="?page={{ imgs.previous_page_number }}">&laquo&laquo</a>
{% endif %}
<button class="btn btn-success">Page {{ imgs.number }}</button>
{% if imgs.has_next %}
    <a class="btn btn-default" href="?page={{ imgs.next_page_number }}">&raquo&raquo</a>
    <a class="btn btn-default" href="?page={{ imgs.paginator.num_pages }}">{{ imgs.paginator.num_pages }}</a>
{% endif %}
</div>
{% endblock %}

index/templates/upload.html
{% extends 'base.html' %}
{% block 'content' %}
{% if err %}
<div class="alert alert-danger">
  {{err}}
</div>
{% endif %}
{% if ok %}
<div class="alert alert-success">
  {{ok}}
</div>
{% endif %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Залить" class="btn btn-primary">
</form>
{% endblock %}

index/templates/user.html
{% extends 'base.html' %}
{% block 'content' %}
<h1>{{user.username}}</h1>
<h3>Rating: {{rating}}</h3>
<div class="row">
<h3>Последние картинки: </h3>
{% for img in imgs %}
<div class="col-md-3" style="height: 300px">
  <img class="img-responsive center-block" src="{{img.img_url}}" alt="" style="max-height: 100%">
</div>
{% endfor %}
</div>
{% endblock %}