api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('',views.index,name='index'),
    path('image/',views.images,name='image'),
    path('user/',views.users,name='users'),
    path('user/<int:uid>/',views.get_user,name='get_user'),
    path('top/<str:bump>/',views.top,name="top")
]

bump/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('myauth.urls')),
    path('api/',include('api.urls')),
    path('',include('index.urls')),
]

index/urls.py
from django.urls import path,include
from . import views

app_name = 'index'

urlpatterns = [
    path('',views.index,name='index'),
    path('pull/<int:img_id>',views.pull,name='pull'),
    path('top',views.bump,name='bump'),
    path('top/<str:bump>',views.bump,name='top'),
    path('user/',views.user,name='user'),
    path('user/<int:uid>',views.user,name='userid'),
    path('loadimg/',views.loadimg,name='loadimg'),
    path('dev/',views.token,name='token'),
    path('dev/new_token',views.new_token,name='new_token')
]

myauth/urls.py
from django.urls import path
from . import views

app_name = 'myauth'

urlpatterns = [
  path('',views.auth,name='login'),
  path('logout/',views.log_out,name='logout'),
  path('reg/',views.reg,name='reg')
]

myauth/models.py
from django.db import models

# Create your models here.

myauth/forms.py
from django.forms import CharField, Form, PasswordInput, EmailField
from django import forms
from django.contrib.auth.validators import ASCIIUsernameValidator

class RegForm(Form):
    login = CharField(label='Login:',max_length=100,
        error_messages = {'required' : 'Укажите логин',
            'invalid' : 'Логин должен содержать только латинские символы и цифры '},
        widget = forms.TextInput(attrs = {'class' : 'form-control'}),
        validators = [ASCIIUsernameValidator()])
    email = EmailField(label='Email:',max_length=100,
        widget = forms.EmailInput(attrs = {'class' : 'form-control'}),
        error_messages = {'required' : 'Укажите email','invalid' : 'Введите валидный email' })
    pwd = CharField(label='Password:',max_length=100,
        error_messages = {'required' : 'Укажите пароль',
            'invalid' : 'Пароль должен содержать только латинские символы и цифры '},
        widget = PasswordInput(attrs = {'class' : 'form-control'}),
        validators = [ASCIIUsernameValidator()])
    pwd2 = CharField(label='Password again:',max_length=100,
        error_messages = {'required' : 'Укажите пароль ещё раз',},
        widget = PasswordInput(attrs = {'class' : 'form-control'}))

    def clean(self):
        if self.cleaned_data.get('pwd') != self.cleaned_data.get('pwd2'):
            raise forms.ValidationError('Пароли должны совпадать!')
        return self.cleaned_data

myauth/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.db.utils import IntegrityError
from .forms import RegForm

# Вспомогательные функции

def get_of_false(obj,**kwargs):
    try:
        return obj.get(**kwargs)
    except User.DoesNotExist:
        return False

def not_login(func):
    def ret_me(*args,**kwargs):
        request = args[0]
        if not request.user.is_authenticated:
            return func(*args,**kwargs)
        else:
            return redirect('/')
    return ret_me

# Собственно, контроллеры
@not_login
def auth(request):
    try:
        uname = request.POST['login']
        upass = request.POST['pwd']
        user = authenticate(request,username=uname,password=upass)
        if not user:
            data = {
                'err' : 'Неправильный логин или пароль',
            }
            return render(request,'login.html',data)
        else:
            login(request,user)
            if 'next' in request.GET:
                return redirect(request.GET['next'])
            return redirect(reverse('index:index'))
    except KeyError:
        return render(request,'login.html',{})

def log_out(request):
    logout(request)
    return redirect('index:index')

@not_login
def reg(request):
    if request.method == "GET":
        return render(request,'reg.html',{'form' : RegForm(),})
    try:
        form = RegForm(request.POST)
        if not form.is_valid():
            newform = RegForm()
            return render(request,'reg.html',{'form' : newform, 'errors' : form.errors})
        uname = request.POST['login']
        uemail = request.POST['email']
        upass = request.POST['pwd']
        user = get_of_false(User.objects,username=uname)
        if user:
            return render(request,'reg.html',{'err' : 'Логин занят!', 'form' : form})
        user = User.objects.create_user(uname,uemail,upass)
    except IntegrityError:
        '''
        Этот костыль создан с целью обойти баг Django, т.к исключение
        генерируется даже когда логина не существует
        '''
        pass

    if user is not None:
        login(request,user)
    if 'next' in request.GET:
        return redirect(request.GET['next'])
    return redirect(reverse('index:index'))

myauth/templates/auth.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Bump or Sage</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <style>
    body {
        padding-top: 70px;
        /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
    }
    </style>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'index:index' %}">BUMP OR SAGE</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'index:top' 'bump' %}">TOP BUMP</a>
                    </li>
                    <li>
                        <a href="{% url 'index:top' 'sage' %}">TOP SAGE</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <div class="row">
            <div class="col-lg-12 text-center">
              {% block 'content' %}
              {% endblock %}
            </div>
        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- jQuery Version 1.11.1 -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>

</html>

myauth/templates/login.html
{% extends 'auth.html' %}
{% block 'content' %}
{% if err %}
<div class="alert alert-danger">
  {{err}}
</div>
{% endif %}
<h3>Войти или <a href="{% url 'myauth:reg' %}">Зарегистрироваться</a></h3>
<form method="POST">
  {% csrf_token %}
  <b>Логин:</b>
  <input name="login" class="form-control"><br>
  <b>Пароль:</b>
  <input name="pwd" type="password" class="form-control"><br>
  <input type="submit" value="Войти" class="btn btn-primary">
</form>
{% endblock %}

myauth/templates/reg.html
{% extends 'auth.html' %}
{% block 'content' %}
{% if err %}
<div class="alert alert-danger">
{{err}}
</div>
{% endif %}
{% if errors %}
<div class="alert alert-danger">
{% for k,err in errors.items %}
{{err}}
{% endfor %}
</div>
{% endif %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Зарегистрироваться" class="btn btn-primary">
</form>
{% endblock %}